_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

#"coco_train_mask_pos", "coco_rib_box_0331_train",  , "coco_rib_dot_0331_train" "coco_train_mask_pos",  "coco_rib_dot_0331_train" "coco_rib_dot_0331_train",

DATASETS:
  TRAIN_LABEL: ("coco_rib_box_0331_train", "coco_rib_box_0331_train", "coco_rib_box_0331_train", "coco_rib_dot_0331_train", )
  TRAIN_NEG: ("coco_rib_box_0331_train_neg", )
  TRAIN_UNLABEL: ("coco_rib_slice_0331_train", )
  TEST: ("coco_rib_val_0331_train",)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 16
  IMG_PER_BATCH_LABEL: 3
  IMG_PER_BATCH_UNLABEL: 2
  IMG_PER_BATCH_NEG: 3
  BASE_LR: 0.003  # Note that RetinaNet uses a different default learning rate
  STEPS: (15000, 30000)
  MAX_ITER: 40000

SEMISUPNET:
  BURN_UP_STEP: 900000
  BBOX_THRESHOLD: 0.5
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.996
  UNSUP_LOSS_WEIGHT: 4.0

INPUT:
  MIN_SIZE_TRAIN: (1024,)

TEST:
  EVAL_PERIOD: 2500

OUTPUT_DIR: "output/blendmask/R_50_1x"

