_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: FCOS
    
DATASETS:
  TRAIN_BOX: ("coco_train_mask_0617_pos", )
  TRAIN_DOT: ("coco_train_mask_0617_pos", )
  TRAIN_MASK: ("coco_train_mask_0617_pos", )
  TRAIN_NEG: ("coco_train_mask_0617_neg", )
  TRAIN_UNLABEL: ("coco_train_mask_0617_pos", )
  TEST: ("coco_val_mask_0617",)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 16
  IMG_PER_BATCH_BOX: 1
  IMG_PER_BATCH_DOT: 1
  IMG_PER_BATCH_MASK: 1
  IMG_PER_BATCH_UNLABEL: 2
  IMG_PER_BATCH_NEG: 1
  BASE_LR: 0.003  # Note that RetinaNet uses a different default learning rate
  STEPS: (20000, 40000)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 2500
  WARMUP_ITERS: 1000

SEMISUPNET:
  BURN_UP_STEP: 900000
  BBOX_THRESHOLD: 0.5
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.996
  UNSUP_LOSS_WEIGHT: 4.0

TEST:
  EVAL_PERIOD: 2500

OUTPUT_DIR: "output/blendmask/R_50_1x"

INPUT:
  MIN_SIZE_TRAIN: (1024, 1024)
  MAX_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MIN_SIZE_TRAIN_SAMPLING: choice